# Generated by Django 2.2 on 2021-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('input_id', models.IntegerField()),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField(max_length=2000)),
            ],
        ),
    ]
