# Generated by Django 2.2.12 on 2021-09-12 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizid', models.IntegerField()),
                ('score', models.IntegerField()),
                ('timetaken', models.IntegerField()),
                ('result', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerid', models.IntegerField()),
                ('questionname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.QuestionsList')),
            ],
        ),
        migrations.AddField(
            model_name='questionslist',
            name='quizname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserResponse'),
        ),
    ]
