# Generated by Django 2.2.12 on 2021-09-12 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionslist',
            name='quizname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_set', to='user_app.UserResponse'),
        ),
        migrations.AlterField(
            model_name='responselist',
            name='questionname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_set', to='user_app.QuestionsList'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='quizid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
