# Generated by Django 2.2.12 on 2021-09-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210912_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionslist',
            name='questionid',
            field=models.CharField(max_length=100),
        ),
    ]
