# Generated by Django 2.2 on 2021-11-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20210913_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responselist',
            name='questionname',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='username',
        ),
        migrations.DeleteModel(
            name='QuestionsList',
        ),
        migrations.DeleteModel(
            name='ResponseList',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
